"""added subchunk_id

Revision ID: 2e8f13bf4454
Revises: f12a8aa20163
Create Date: 2024-12-06 22:50:42.213550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8f13bf4454'
down_revision: Union[str, None] = 'f12a8aa20163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('subchunk_id', sa.Integer(), nullable=True),
    sa.Column('discord_message_id', sa.String(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_chunks_subchunk_id'), 'file_chunks', ['subchunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_chunks_subchunk_id'), table_name='file_chunks')
    op.drop_table('file_chunks')
    op.drop_table('folders')
    # ### end Alembic commands ###
