"""remove subchunk_id

Revision ID: 85bc0d903263
Revises: 2e8f13bf4454
Create Date: 2024-12-06 23:19:59.876651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bc0d903263'
down_revision: Union[str, None] = '2e8f13bf4454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_chunks_subchunk_id', table_name='file_chunks')
    op.drop_column('file_chunks', 'subchunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('subchunk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_file_chunks_subchunk_id', 'file_chunks', ['subchunk_id'], unique=False)
    # ### end Alembic commands ###
