"""added subchunk_id

Revision ID: f12a8aa20163
Revises: 
Create Date: 2024-12-06 22:48:52.080828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12a8aa20163'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_chunks')
    op.drop_table('folders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('folders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='folders_pkey'),
    sa.UniqueConstraint('name', name='folders_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('file_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discord_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name='file_chunks_folder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_chunks_pkey')
    )
    # ### end Alembic commands ###
